### PR TITLE
Add Service Fabric bootstrapper

### PR DESCRIPTION
**Pull request by pshrosbree**
Add Service Fabric bootstrapper that sets up Akka.Cluster by reading from Service Fabric created environment variables 
Update to netstandard2.0
Update to Akka 1.3.9
Update to FluentAssertions 5.4.1
Update Microsoft.NET.Test.Sdk to 15.8.0
Update XUnit to 2.4.0
Fix some spelling errors

### CODE REVIEW

**Comment by pshrosbree** [comment]
@Aaronontheweb perhaps `Akka.Bootstrap.Docker` is no longer the correct name.
How about `Akka.Bootstrap`?

**Comment by Aaronontheweb** [comment]
@pshrosbree sorry for the delay, our build server had some issues 24 hours ago with our Azure Windows Agents not authenticating correctly and I've had the build queue paused. I'll need to get that resolved :p 

As far as package names go: want to communicate that this is a tool for helping Akka.NET users get the relevant binding / cluster information in their chosen environment. I think the current names seem to do that reasonably well - what do you think?

**Comment by pshrosbree** [comment]
I am happy with the names. I misunderstood how the packages were created.
It may be an idea to add a Petabridge.Cmd bootstrapper.

**Comment by Aaronontheweb** [comment]
Looks like we're still having some TeamCity issues with our Windows agents - thought I had fixed it today but the agents are having some trouble authorizing after we push the installer onto them. Weird. 

@pshrosbree 

> It may be an idea to add a Petabridge.Cmd bootstrapper.

I think that'd be an excellent idea. Do you mean add some port bindings for an incoming Petabridge.Cmd endpoint in these templates? Or a new template altogether?

**Comment by pshrosbree** [comment]
Either a flag in the current bootstrappers, or a completely separate bootstrapper.

**Comment by Aaronontheweb** [comment]
@pshrosbree I think a flag in the current bootstrapper would be a good idea

**Comment by pshrosbree** [comment]
I agree.

**Comment by Aaronontheweb** [comment]
Ah, looks like the build server didn't like the upgrade to the 2.1 SDK. I'll just need to upgrade the build scripts. I'll take care of that now.

**Comment by Aaronontheweb** [comment]
I'll do the update in a new PR I think

**Comment by pshrosbree** [comment]
Thanks.
:)

**Pull request merged**
